export const showTiles = () => {
  return ([
    {
      title: "Spinner Wheel",
      link: "/spinner-wheel",
      description: "Spin a wheel!",
      logo: "spinner-wheel-logo",
      category: "Probability",
    },
    {
      title: "Scoreboard",
      link: "/scoreboard",
      description: "Record your victories!",
      logo: "scoreboard-logo",
      category: "Game Tools",
    },
    {
      title: "Matchups",
      link: "/matchups",
      description: "Host a knockout tournament!",
      logo: "matchups-logo",
      category: "Game Tools",
    },
    {
      title: "Dice",
      link: "/dice",
      description: "Roll dice!",
      logo: "dice-logo",
      category: "Probability",
    },
    {
      title: "Timer",
      link: "/timer",
      description: "Time stuff!",
      logo: "timer-logo",
      category: "Utilities",
    },
    {
      title: "Coin Flipper",
      link: "/coin-flipper",
      description: "Flip coins!",
      logo: "coin-logo",
      category: "Probability",
    },
    {
      title: "Random Number Generator",
      link: "/rng",
      description: "Generate a random number!",
      logo: "rng-logo",
      category: "Probability",
    },
    {
      title: "Date Calculator",
      link: "/date-calculator",
      description: "Find days between dates!",
      logo: "date-calculator-logo",
      category: "Utilities",
    },
    {
      title: "Operations",
      link: "/operations",
      description: "Do some quick maths to reach the target number!",
      logo: "operations-logo",
      category: "Games",
    },
    {
      title: "Base64",
      link: "/base64",
      description: "Encode and decode in Base 64!",
      logo: "base64-logo",
      category: "Text Tools",
    },
    {
      title: "Text Converter",
      link: "/text-converter",
      description: "Convert your text!",
      logo: "text-converter-logo",
      category: "Text Tools",
    },
    {
      title: "Lorem Ipsum",
      link: "/lorem-ipsum",
      description: "Generate Lorem Ipsum placeholder text!",
      logo: "lorem-ipsum-logo",
      category: "Text Tools",
    },
    {
      title: "Password Checker",
      link: "/password-checker",
      description: "Check your password strength!",
      logo: "pw-checker-logo",
      category: "Utilities",
    },
    {
      title: "Memory",
      link: "/memory",
      description: "Beat the puzzle in as few flips as possible!",
      logo: "memory-logo",
      category: "Games",
    },
    {
      title: "Tic Tac Toe",
      link: "/tictactoe",
      description: "Play a classic game of Tic Tac Toe!",
      logo: "tictactoe-logo",
      category: "Games",
    },
    {
      title: "Speech to Text",
      link: "/speech-to-text",
      description: "Convert your speech into text!",
      logo: "stt-logo",
      category: "Utilities",
    },
    {
      title: "Random Card Generator",
      link: "/card-generator",
      description: "Generate random poker cards!",
      logo: "card-logo",
      category: "Probability",
    },
  ])
}